[metadata]
name = alma-rc
version = 0.1.0
author = Rafael Martinez Estevez
author_email = malayibiri@gmail.com
description = DSpace to InvenioRDM migration tool for ALMA repository
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/tocororo/alma-rc
project_urls =
    Bug Tracker = https://github.com/tocororo/alma-rc/issues
classifiers =
    Development Status :: 4 - Beta
    Intended Audience :: Developers
    License :: OSI Approved :: MIT License
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.12
    Topic :: Software Development :: Libraries :: Python Modules
    Topic :: System :: Archiving
    Topic :: Text Processing

[options]
package_dir = 
    = src
packages = find:
python_requires = >=3.12
install_requires =
    lxml>=6.0.0,<7.0.0
    sickle>=0.7.0,<1.0.0
    datamodel-code-generator>=0.33.0,<0.34.0
    requests>=2.32.4,<3.0.0
    pydantic>=1.10.22,<2.0.0
    pandas>=2.3.3,<3.0.0
    rapidfuzz>=3.14.1,<4.0.0
    pycountry>=24.6.1,<25.0.0
    dateparser>=1.2.2,<2.0.0
    python-dotenv>=1.2.1,<2.0.0
    idutils>=1.5.0,<2.0.0
    certifi>=2025.7.14

[options.packages.find]
where = src

[options.entry_points]
console_scripts =
    alma-rc = alma_rc.insert_data.import:main